### ISSUE TITLE
[API] Add API to get context

### ISSUE THREAD

**Issue by NoumbissiValere** [openwisp/django-netjsonconfig#118]
Add an API which will be used to get the full context of a Device. 
The data for this API will be used for varaible-context validation with javascript

**Comment by nemesisdesign** [comment]
:+1:

**Comment by nemesisdesign** [comment]
Adding some details for **GCI students**.

The API view should be accessible only to users which are logged in the admin, and should be included in a similar way to how the schema view is now included, see https://github.com/openwisp/django-netjsonconfig/blob/master/django_netjsonconfig/base/admin.py#L92.

Ensure changes follow our style conventions and write tests for it (test coverage shall not decrease).

**Comment by oltarzewskik** [comment]
starting working on it :+1:
