### ISSUE TITLE
[enhancement] Duplication of action list, save row

### ISSUE THREAD

**Issue by nepython** [openwisp/django-netjsonconfig#159]
**Duplicate display of action list**
![Screenshot from 2020-03-09 17-09-57](https://user-images.githubusercontent.com/54471024/76227920-eab93e80-6217-11ea-8c31-854954fee855.png)

**Duplicate display of submit row**
![Screenshot from 2020-03-09 17-42-24](https://user-images.githubusercontent.com/54471024/76227928-edb42f00-6217-11ea-87ee-63221454eaf4.png)

**Comment by nepython** [comment]
I traced the cause of it and it seemed as if it has been done on purpose, so @nemesisdesign can you please confirm if these are required or else I move ahead and fix it. :grinning:

**Comment by atb00ker** [comment]
Yes this is on purpose, all django admin pages are designed like this. These sections are on the top and the bottom of the page! :smile:

**Comment by nemesisdesign** [comment]
It's very useful when the system is fully working and there's some content in it. 
It looks weird when the system is empty.

**Comment by nepython** [comment]
![Screenshot from 2020-03-09 21-10-47](https://user-images.githubusercontent.com/54471024/76231471-34f0ee80-621d-11ea-9b32-9257907aa08d.png)
Though I think it can be removed from some places like the one above.

**Comment by nemesisdesign** [comment]
Not a priority right now, focus on the priorities
