### ISSUE TITLE
[admin] 404 on Device change page raises 500 internal server error

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#165]
How to replicate:

- open device admin list
- open a device change page with the UUID modified so to trigger a 404

Expected result: 404

Actual result: 500 internal server error.

A test to ensure we won't have regressions will be needed.

**Comment by nepython** [comment]
> A test to ensure we won't have regressions will be needed.

@nemesisdesign, is the test supposed to ensure that we get a **404** error when trying to access a page with a URL containing the wrong uuid, while we get a status code of **200** when trying to access the same page with uuids present in the database `or` I am also supposed to ensure that I don't break anything or reintroduce old bugs (If so is the case, can you please guide me to those bugs).

**Comment by nemesisdesign** [comment]
@nepython write a test which fails with the bugged version of the code (before you apply the fix), then apply the fix and ensure the test passes. The test should expect 404, there should be [similar tests](https://github.com/openwisp/django-netjsonconfig/blob/ce410f8cca0936c44004772f277d5fee2d5a3f26/django_netjsonconfig/tests/test_admin.py#L97-L101) already so you just need to adapt one.
