### ISSUE TITLE
[x509] VPN client files should be created with 0600 permissions by default.

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#169]
VPN client files (ca, cert, key) should be created with 0600 permissions by default.

**Comment by TheOneAboveAllTitan** [comment]
Working on this!

**Comment by TheOneAboveAllTitan** [comment]
@nemesisdesign it is kinda hardcoded [in netjsonconfig](https://github.com/openwisp/netjsonconfig/blob/75a77efdc9782b0d16b910b82f2d7f58951da232/netjsonconfig/backends/openvpn/openvpn.py#L124). One way can be to make DEFAULT_FILE_MODE a class variable, whose value is updated from schema.

**Comment by nemesisdesign** [comment]
@TheOneAboveAllTitan thanks for the analysis, I think this is the way to go:
https://github.com/openwisp/netjsonconfig/issues/147#issuecomment-602113886

The problem is downstream. The test in this module will need to be updated like you did in https://github.com/TheOneAboveAllTitan/django-netjsonconfig/commit/7bb6c8177622b923d586797daa358660f9753cb1.

**Comment by nemesisdesign** [comment]
So now that https://github.com/openwisp/netjsonconfig/pull/148 is merged, here it remains pending to verify that the fix works when used via the admin and then we can close this as well.
