### ISSUE TITLE
[UI] Improve advanced editing (raw json) mode

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#23]
Editing raw json it's currently uncomfortable for various reasons:
- json syntax errors are not shown
- no syntax highlighting
- no full-screen editing possible

Something like [this tool](https://github.com/josdejong/jsoneditor) could improve usability a lot.

**Comment by rohithasrk** [comment]
Implementing this would solve #30 too. Will start working soon. :)

**Comment by gastonche** [comment]
Working on this now issue right now
