### ISSUE TITLE
[Config] get rid of monkey patching in sortedm2m

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#29]
Improve the change implemented in https://github.com/openwisp/django-netjsonconfig/commit/96f4d09f0ab0fe0950fb1aa6363933057e6e7203 by supplying a patch to **django-sortedm2m**, see https://github.com/gregmuellegger/django-sortedm2m/issues/96.

**Comment by rohithasrk** [comment]
Yeah. Will look into it.

**Comment by nemesisdesign** [comment]
ok @rohithasrk it would be great if you could solve this. It's an interesting challenge. If you can't work on it let me know, I will have to do this soon because it's causing me to duplicate some code and I don't like this.

**Comment by rohithasrk** [comment]
I see. Will try solving it ASAP.

**Comment by rohithasrk** [comment]
@nemesisdesign : Made a (PR)[https://github.com/gregmuellegger/django-sortedm2m/pull/101] in django-sortedm2m. Please review it.

**Comment by nemesisdesign** [comment]
@rohithasrk great, replied there

**Comment by nemesisdesign** [comment]
Now we can finally upgrade the django-sortedm2m to be higher or equal to 1.5.0 and remove the monkey patching :-)
