### ISSUE TITLE
[admin] JSON syntax errors not reported properly

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#30]
Bug explanation: [(openwisp-mailing-list) Error when using advanced mode template](https://groups.google.com/d/msg/openwisp/G2_fXZtiQVM/MM7vIhJbAgAJ).

**Comment by rohithasrk** [comment]
Will work on it.

**Comment by rohithasrk** [comment]
Adding try-catch blocks in `/django-netjsonconfig/static/django-netjsonconfig/js/jsonschemaeditor_widget.js` would be a trivial solution to this problem. Any alternative/clean way of solving this problem?

**Comment by nemesisdesign** [comment]
This was fixed by #40. Thank you both @rohithasrk and @gastonche

**Comment by gastonche** [comment]
@nemesisdesign , I think my PR on #23 should have fixed this issue.
