### ISSUE TITLE
[sortedm2m] Make widget hint bolder

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#31]
The help text *"Choose items and order by drag & drop"* in the sortedm2m widget is helpful but hard to see. 

Users have suggested to make it more evident.

**Comment by rohithasrk** [comment]
Working on it.

**Comment by rohithasrk** [comment]
Just checked the code. Seems that it is in django-sortedm2m package and not in the django-netjsonconfig package. I understand that we need to make the text more intuitive by making it bolder. May take a while to figure out a way to edit a particular line css of a widget. Suggestions are welcome.

**Comment by nemesisdesign** [comment]
@rohithasrk you can ude this file: https://github.com/openwisp/django-netjsonconfig/blob/master/django_netjsonconfig/static/django-netjsonconfig/css/admin.css

**Comment by rohithasrk** [comment]
I see. Thanks. Will submit a PR sometime today. :)

**Comment by rohithasrk** [comment]
Check out #32 @nemesisdesign
