### ISSUE TITLE
[sortedm2m] Make the help_text appear somewhere else

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-netjsonconfig#33]
When there is some text data given to `SortedManyToManyField()` as a `help_text` parameter, the way it is displayed is not at all intuitive. Check the screenshot attached below.
![help_text_error](https://cloud.githubusercontent.com/assets/13820931/23549055/5e4e26e6-0030-11e7-8af6-cd8eb5fa495f.png)
Here, `help_text=_('configuration templates, applied from first to last')`
This needs to be made more intuitive.

**Comment by nemesisdesign** [comment]
I just pushed fa9be300d0355a61b823445af5b415543509dd14, it could be good enough, check it out and tell me what you think

**Comment by rohithasrk** [comment]
Seems fine now.

**Comment by nemesisdesign** [comment]
@rohithasrk can this issue be closed?

**Comment by rohithasrk** [comment]
Yes. I'm closing this.
