### ISSUE TITLE
[UI] Full screen for advanced mode

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#41]
When going into advanced mode, it would be nice to have the possibility to edit the JSON in full screen mode.

The hint *"Want learn to use the advanced mode? Consult the netjsonconfig documentation.*" should be kept. 

I think it would also be ok to have the full screen mode as default, but I leave this open for discussion.

**Comment by gastonche** [comment]
Okay @nemesisdesign i am working on this right now

**Comment by nemesisdesign** [comment]
Let's continue the discussion on #45
