### ISSUE TITLE
[UI] configuration variables clash with validation

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#44]
The following NetJSON:

```javascript
{
    "interfaces": [
        {
            "type": "virtual",
            "name": "tap0",
            "mac": "{{ mac_address }}"
        }
    ]
}
```

Won't validate. This sucks big time! 

We should find a solution for this problem. Maybe we can evaluate the variables with javascript. I don't know.

**Comment by yasharmaster** [comment]
I'm working on this.

**Comment by nemesisdesign** [comment]
@yasharmaster let us know how you intend to solve it once you get an idea

**Comment by saksham1115** [comment]
How can I recreate this validation ?

**Comment by adriankirchner** [comment]
@yasharmaster @nemesisdesign are there any updates on this? If I get that right, atm it is not possible to eg. specify the lan ipv4 address via a custom variable.
Therefore I can't use a template to configure the eth0 interface but need to add this configuration to every device manually
![screenshot-openwisp adrian-kirchner com-2018 04 22-14-48-15](https://user-images.githubusercontent.com/149483/39095159-7ae57414-463c-11e8-9e78-75dafff18781.png)

**Comment by nemesisdesign** [comment]
@adriankirchner as far as I know, nobody is currently actively working on this issue

**Comment by nemesisdesign** [comment]
@adriankirchner solving this will require some work, I've created #93 to summarize the different actions required to fix it.

**Comment by nemesisdesign** [comment]
Fixed by https://github.com/openwisp/django-netjsonconfig/pull/178
