### ISSUE TITLE
[UI] full screen covers preview

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#49]
Full screen mode covers preview config mode.

It's probably just a matter of adjusting `z-index` css property so the ones of the preview is higher.

@gastonche would you like to address this?

**Comment by gastonche** [comment]
I'll Address that right away @nemesisdesign

**Comment by gastonche** [comment]
@nemesisdesign, Can't reproduce the full screen covering preview. Please directions

**Comment by nemesisdesign** [comment]
@gastonche right, sorry I didn't explain you everything.

There's a shortcut for preview mode, which is ALT+P. If you use this shortcut while in full screen mode you will notice nothing happens. Try then to close the full screen and you will see the preview.

**Comment by nemesisdesign** [comment]
thx for fixing this @gastonche
