### ISSUE TITLE
[json_editor] Alignment issue

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-netjsonconfig#59]
A minor alignment issue that I've encountered while using the application. Look at the 'netjsonconfig documentation' text in the image below.

![alignement](https://user-images.githubusercontent.com/13820931/27119663-5c8db05a-50fe-11e7-8ab3-96cf185f5df3.png)

**Comment by nemesisdesign** [comment]
@rohithasrk thx for reporting. Which browser and OS?

**Comment by rohithasrk** [comment]
Ubuntu 14.04 and I use firefox.
