### ISSUE TITLE
Add hostname validator to Device.name

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#62]
How to reproduce the issue: try to save a new device with name `test device`.
Result: netjsonconfig validation complains test device is not a valid hostname and the validation error is shown in the configuration section.
Fix: it would be better to show this validation error relating directly to the name field

**Comment by R9295** [comment]
@nemesisdesign I was able to create a new device with the name set to `test device`. I didn't receive a validation error.

**Comment by R9295** [comment]
![no_validation_error](https://screenshots.firefoxusercontent.com/images/28e93706-7a8e-44ff-be9e-9b19d4731f2e.png)

**Comment by nemesisdesign** [comment]
try creating a new device and also a configuration (scroll down, click "add configuration")
the error is triggered by the configuration, which is a oneToOne optional relation between Device and Config
