### ISSUE TITLE
[rare] Auto-registration fails but device is created anyway

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#64]
In rare cases, auto-registration may fail because of misconfiguration or bugs introduced during development.

It then may happen that even if the auto-registration fails, the device may be created anyway, eg: if the uncaught exception is triggered in the phase which adds templates (m2m relationship in django are saved after the main object has been created).

This is not good because it triggers other unexpected behaviour, a chain reaction which is hard to debug.
The ideal solution would be to ensure to catch any potential exception during all the critical phases of the autoregistration and if any of these phases fails, the system should log the error, trigger something like a 400 bad request and delete the newly created invalid device.

**Comment by pacicap** [comment]
i am interested in solving this issue please may i have some tips on how to get started?

**Comment by pacicap** [comment]
please on which file should i concentrate the most i am not very familiar with javascript

**Comment by atb00ker** [comment]
@pacicap Hey please join the gitter channel to ask questions, sometimes the questions here get lost in the noise! :smile:
