### ISSUE TITLE
[admin] Download configuration 404 if no configuration 

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/django-netjsonconfig#66]
Try to create a new device with no configuration, then click on "download", you will notice a 404.

It would be better to tell there's no configuration available yet and advice to create one.

The preview button gives an alert "no configuration available yet", we should add there an advice to create one.

**Comment by Kelvin-DeCosta** [comment]
Please review my implementation :smile:

**Comment by R9295** [comment]
@nemesisdesign I'd like to do this next.
