### ISSUE TITLE
Python2 issues

### ISSUE THREAD

**Issue by UtkarshVerma** [openwisp/django-netjsonconfig#72]
When using Python2 for its installation, it fails because django v2.0.1 is fetched as a requirement which is unsupported by Python2.

**Comment by h0n3yc4k3** [comment]
Just add note that django-netjsonconfig fetching django v2.0.1, so before installing that you should install `django~=1.0` :)
Its way to bypass this error

**Comment by UtkarshVerma** [comment]
Its a workaround not a fix.

**Comment by h0n3yc4k3** [comment]
Yes :(

**Comment by nemesisdesign** [comment]
For python 2 the solution is:
```
pip install django==1.11
python setup.py develop
```
Python 2 support is going to be dropped soon anyway so there's no need to spend energy on this.

Thanks for reporting!
